// File: peserta.js
window.DATA_PESERTA = [
  { "no": "01", "nama": "Ahmad Fadhsya Hasyim", "link": "https://drive.google.com/drive/folders/1fMwOy98D2RChZ2DalRx149_gLy092B1F" },
  { "no": "02", "nama": "Ahmad Khadavi", "link": "https://drive.google.com/drive/folders/1Yd2ALOh-elrWXbD9eSc8ITGr5tckBwS_" },
  { "no": "03", "nama": "ALFIAN", "link": "https://drive.google.com/drive/folders/19sCcbl044TAjC61g94mQqfsM83Atayv_" },
  { "no": "04", "nama": "Alika Tsuraya Ostman", "link": "https://drive.google.com/drive/folders/1mJL56QT5Wwml3E9o2xDewjZxi-eczfkw" },
  { "no": "05", "nama": "ALMIRA PUSPANING JAGAD", "link": "https://drive.google.com/drive/folders/126WQVkOIVCLB5rKFt9QgjXCDUhxn7gmj" },
  { "no": "06", "nama": "AS SHAFIRA QINAYA", "link": "https://drive.google.com/drive/folders/15jR4SHT3G9tGJImkVqE01K3eCLmO2w6q" },
  { "no": "07", "nama": "Asfa Dzaki Nur Fathan", "link": "https://drive.google.com/drive/folders/1OEF_pANqy0uCNlV4XBuF-vr6-BUSdDto" },
  { "no": "08", "nama": "AZELIA SAMARA BALQIS", "link": "https://drive.google.com/drive/folders/1j3g2pUvt2j4H5zhn8yvmqzqiKGApXrJU" },
  { "no": "09", "nama": "CHRISTIAN JULIO BADAR", "link": "#" },
  { "no": "10", "nama": "Davinza Ardi Pratama", "link": "https://drive.google.com/drive/folders/1QDjvtgioN3V3Bi6XJHF0rozF5d_bcNPG" },
  { "no": "11", "nama": "Deo Tegar Prayer Dien", "link": "https://drive.google.com/drive/folders/1wN6-mwTvAPz0WF7veL4UtW2aX-sgG7t-" },
  { "no": "12", "nama": "Deshenier Meixing Zulkarnain", "link": "https://drive.google.com/drive/folders/16Vay_A76zEYPEbdcfG_upMd5M9fn9-I_" },
  { "no": "13", "nama": "DESI BOARI", "link": "https://drive.google.com/drive/folders/1V7zhqkO6KUijNkOA-xpptcTtRLmHvOkd" },
  { "no": "14", "nama": "Deven Edward Michael", "link": "https://drive.google.com/drive/folders/1oyp4T8AL8Bi71M2Ctvuikd-4KyD_2b5O" },
  { "no": "15", "nama": "DIMAS ARYO SENA", "link": "https://drive.google.com/drive/folders/1mX319dausTOg6K4mJzqgUSqKBYWXDbXt" },
  { "no": "16", "nama": "Dimas Fikry Fahrezy", "link": "https://drive.google.com/drive/folders/1CoOTrIbx907l7VbCfPHWdvaPqZk3XI09" },
  { "no": "17", "nama": "Fransiskus Xaverius Geraldo", "link": "https://drive.google.com/drive/folders/14fNzvAKWaTrtbeNM2B0P4YC7bN-oF0Fp" },
  { "no": "18", "nama": "I Made Gilang Darmawan", "link": "https://drive.google.com/drive/folders/1AAO3dX9MmQq4o1e_6uYLURLs_tJpKu_j" },
  { "no": "19", "nama": "Maimunah Nursarah", "link": "https://drive.google.com/drive/folders/1yMc6UZD9RtL_NHpTT0fp7VDkQNvI_cs0" },
  { "no": "20", "nama": "Muhammad Danish Zafran Atayallah", "link": "https://drive.google.com/drive/folders/1zLhxLI-118vFPTdDvo0AgERLHKhGmjkb" },
  { "no": "21", "nama": "Muhammad Nabil Al Ghifari", "link": "https://drive.google.com/drive/folders/1MDvuAQeDFl4YsH0f4O5_3ItGVetvg9Fb" },
  { "no": "22", "nama": "Muhammad Sharul", "link": "https://drive.google.com/drive/folders/1AuPT2NRtNxleMxT4hcTz68VWobGqBnPz" },
  { "no": "23", "nama": "Muhammad Yoga Permana", "link": "https://drive.google.com/drive/folders/1KqgQl2fIY5jxOm1o4DMVSR3PsddWAXE6" },
  { "no": "24", "nama": "Nabhan Akbar Arifanny", "link": "https://drive.google.com/drive/folders/10XNo0U5_ijWuYgsNzGo-dYwBFMD7lDBh" },
  { "no": "25", "nama": "Nafisah Aulia", "link": "https://drive.google.com/drive/folders/1Rvr6Ued-_pzIDK73uGuT_i_BYjVhABJE" },
  { "no": "26", "nama": "NIKITA HARUN", "link": "https://drive.google.com/drive/folders/1hJaRmQM4zveYNy5ukAIn1SKBMTbtrxMM" },
  { "no": "27", "nama": "Putri Safa Azahra", "link": "https://drive.google.com/drive/folders/1ENx9atAnF-4JJ37XsSVaCGIZuRD5L8hn" },
  { "no": "28", "nama": "Raissa Vania", "link": "https://drive.google.com/drive/folders/1uEckEXK2IhsWGgOSosLP4p0phZIVO7nq" },
  { "no": "29", "nama": "Rakah Ataullah Syamil", "link": "https://drive.google.com/drive/folders/1XBE4LGVLBvH7px8iElbURawxYXP0eaSM" },
  { "no": "30", "nama": "Resty I Jafar", "link": "https://drive.google.com/drive/folders/1m6jE0lpBPnR2Ard15iCuDp_DCHawlb9W" },
  { "no": "31", "nama": "Syakira Luqyana Pahlavi", "link": "https://drive.google.com/drive/folders/1lKwbyQ-79T4UeYmFSb26QaLmGCj4iekH" },
  { "no": "32", "nama": "Viandra Aura Muliawan", "link": "https://drive.google.com/drive/folders/1vnt1yi87UEjUESd9HTSG8kicJcOK7CCx" }
];
